a simple demo
ilhamadun/WiringPiKeypad pull request #2
Opened 2018-12-27 11:02 UTC by jsxyhelu

a simple demo

2018-12-27 11:02 UTC, jsxyhelu commented
wait to pass

2018-12-27 11:25 UTC, ilhamadun requested changes

2018-12-27 11:25 UTC, ilhamadun commented on README.md
> +    int row[4] = {21, 22, 23, 24};
You should wrap the example in a [code block](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to let github's syntax highlighting to work. Don't forget to add `c++` to the beginning of the code block (the example in the link above uses `ruby`).

2018-12-27 11:25 UTC, ilhamadun commented on README.md
> +    int row[4] = {21, 22, 23, 24};
Without syntax highlighting:
```
int row[4] = {21, 22, 23, 24};
```

With syntax highlighting:
```c++
int row[4] = {21, 22, 23, 24};
```

I mean, who doesn't love color, right?

2018-12-27 11:25 UTC, ilhamadun commented on README.md
> +    {'D', 'C', 'B', 'A'},
The inner vector initialization should be indented to make it easier to read.

```c++
std::vector<std::vector<char>> matrix {
    {'D', 'C', 'B', 'A'},
    {'#', '9', '6', '3'},
    {'0', '8', '5', '2'},
    {'*', '7', '4', '1'}
}
```

is easier to read instead of

```c++
std::vector<std::vector<char>> matrix {
{'D', 'C', 'B', 'A'},
{'#', '9', '6', '3'},
{'0', '8', '5', '2'},
{'*', '7', '4', '1'}
}
```

2018-12-28 12:59 UTC, jsxyhelu commented
that will be better

2018-12-28 12:59 UTC, closed without merging